require('kp.opts')
require('kp.keymaps')

require('kp.packer')
require('kp.nvim-tree')
require('kp.telescope')
require('kp.tree-sitter')
require('kp.lsp')
require('kp.smartbufs')
require('kp.bufferline')
require('kp.expressline')
require('kp.autoclose')
require('kp.indent')
require('kp.lazygit')
require('kp.term')
require('kp.gitsigns')
